[tool.black]
line-lenght = 100
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
    | \.git
    | \.hg
    | \.tox
    | \.venv
    | _build
    | build
    | dist
    | __pycache__
)/
'''